import { Link, useLocation } from "wouter";
import { ArrowLeft, ArrowRight, Check, CheckCircle2, ChevronDown, FileText, LockKeyhole, UploadCloud, UserRound } from "lucide-react";
import { useRef, useState } from "react";

const roles = ["Software Engineer", "Data Analyst", "Product Designer", "Product Manager"];
const experiences = ["Early career · 0–2 years", "Mid-level · 3–5 years", "Senior · 6–9 years", "Lead · 10+ years"];
const initialSkills = [{ name: "Python & APIs", value: 82 }, { name: "System design", value: 61 }, { name: "Cloud architecture", value: 44 }, { name: "Testing & quality", value: 73 }];

export default function CandidateOnboarding() {
  const [, navigate] = useLocation();
  const [step, setStep] = useState(1);
  const [role, setRole] = useState("Software Engineer");
  const [experience, setExperience] = useState(experiences[1]);
  const [skills, setSkills] = useState(initialSkills);
  const [fileName, setFileName] = useState("");
  const [anonymized, setAnonymized] = useState(false);
  const fileRef = useRef<HTMLInputElement>(null);
  const next = () => setStep((value) => Math.min(4, value + 1));
  const back = () => setStep((value) => Math.max(1, value - 1));
  const finish = () => navigate("/candidate/dashboard");
  const simulateResume = (name?: string) => { setFileName(name || "alex-morgan-resume.pdf"); setTimeout(() => setAnonymized(true), 450); };

  return <div className="min-h-screen bg-[#0B0F19] text-slate-100"><div className="mx-auto max-w-6xl px-6 py-7 lg:px-10"><div className="flex items-center justify-between"><Link href="/" className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-indigo-500 text-white"><span className="font-display text-sm font-bold">C</span></span><span className="font-display text-sm font-semibold">CareerCompass <span className="font-normal text-slate-600">/ onboarding</span></span></Link><div className="flex items-center gap-2 text-xs text-slate-500"><LockKeyhole size={13} className="text-emerald-400" />Your data stays yours</div></div>
    <div className="mx-auto max-w-3xl pb-16 pt-16"><div className="mb-12"><div className="mb-4 flex items-center justify-between text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-600"><span>Build your signal</span><span>{step} of 4</span></div><div className="flex gap-2">{[1,2,3,4].map((number) => <div key={number} className={`h-1 flex-1 rounded-full transition ${number <= step ? "bg-indigo-400" : "bg-white/[0.08]"}`} />)}</div></div>
      {step === 1 && <StepFrame eyebrow="Step 01 · target role" title="Where do you want to go next?" description="Choose a destination role so we can compare your current signal to the skills that matter most there."><div className="grid gap-3 sm:grid-cols-2">{roles.map((item) => <button key={item} onClick={() => setRole(item)} className={`flex items-center justify-between rounded-2xl border p-4 text-left transition ${role === item ? "border-indigo-400/50 bg-indigo-400/10 text-white" : "border-white/[0.08] bg-[#111725] text-slate-400 hover:border-white/20"}`}><span className="flex items-center gap-3"><span className={`grid h-9 w-9 place-items-center rounded-xl ${role === item ? "bg-indigo-400/15 text-indigo-300" : "bg-white/[0.04] text-slate-600"}`}><FileText size={16} /></span><span><span className="block text-sm font-semibold">{item}</span><span className="mt-1 block text-[11px] text-slate-500">{item === "Software Engineer" ? "Backend · platform · product" : "A tailored skills comparison"}</span></span></span><span className={`h-4 w-4 rounded-full border ${role === item ? "border-4 border-indigo-300" : "border-white/20"}`} /></button>)}</div></StepFrame>}
      {step === 2 && <StepFrame eyebrow="Step 02 · experience" title="What’s your current altitude?" description="This helps us set a fair baseline. We measure capability, not pedigree or tenure alone."><div className="space-y-3">{experiences.map((item) => <button key={item} onClick={() => setExperience(item)} className={`flex w-full items-center justify-between rounded-2xl border p-5 text-left transition ${experience === item ? "border-indigo-400/50 bg-indigo-400/10" : "border-white/[0.08] bg-[#111725] hover:border-white/20"}`}><span className="flex items-center gap-3"><span className={`grid h-9 w-9 place-items-center rounded-xl ${experience === item ? "bg-indigo-400/15 text-indigo-300" : "bg-white/[0.04] text-slate-600"}`}><UserRound size={16} /></span><span className="text-sm font-semibold text-slate-200">{item}</span></span><span className={`h-4 w-4 rounded-full border ${experience === item ? "border-4 border-indigo-300" : "border-white/20"}`} /></button>)}</div></StepFrame>}
      {step === 3 && <StepFrame eyebrow="Step 03 · resume signal" title="Drop your resume. We’ll remove the noise." description="We strip personal identity fields before scoring so your signal starts with what you can do, not who you are."><div onClick={() => fileRef.current?.click()} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); simulateResume(event.dataTransfer.files[0]?.name); }} className="cursor-pointer rounded-3xl border border-dashed border-indigo-300/30 bg-indigo-400/[0.05] p-10 text-center transition hover:border-indigo-300/60"><input ref={fileRef} type="file" accept=".pdf,.doc,.docx" className="hidden" onChange={(event) => simulateResume(event.target.files?.[0]?.name)} />{fileName ? <><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-emerald-400/10 text-emerald-300"><CheckCircle2 size={25} /></div><p className="mt-4 text-sm font-semibold text-white">{fileName}</p><p className="mt-1 text-xs text-slate-500">Uploaded just now · click to replace</p></> : <><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-indigo-400/10 text-indigo-300"><UploadCloud size={25} /></div><p className="mt-4 text-sm font-semibold text-white">Drop your resume here</p><p className="mt-1 text-xs text-slate-500">PDF or DOCX · up to 10MB</p></>}</div><div className={`mt-4 flex items-start gap-3 rounded-2xl border p-4 transition ${anonymized ? "border-emerald-400/20 bg-emerald-400/[0.07]" : "border-white/[0.07] bg-[#111725]"}`}><div className={`mt-0.5 ${anonymized ? "text-emerald-300" : "text-slate-600"}`}>{anonymized ? <CheckCircle2 size={17} /> : <LockKeyhole size={17} />}</div><div><p className="text-xs font-semibold text-slate-200">{anonymized ? "Identity fields removed" : "Identity-blind scoring"}</p><p className="mt-1 text-[11px] leading-5 text-slate-500">Names, gender, college, email, and location are excluded from your readiness score.</p></div></div></StepFrame>}
      {step === 4 && <StepFrame eyebrow="Step 04 · calibrate" title="How would you rate your skills?" description="Start with your own signal. You can refine it anytime as you make progress."><div className="rounded-2xl border border-white/[0.08] bg-[#111725] p-5 sm:p-6">{skills.map((skill, index) => <div key={skill.name} className={index === skills.length - 1 ? "" : "mb-7"}><div className="mb-3 flex items-center justify-between"><span className="text-sm font-medium text-slate-200">{skill.name}</span><span className="font-mono text-xs text-indigo-300">{skill.value}<span className="text-slate-600"> / 100</span></span></div><input type="range" min="0" max="100" value={skill.value} onChange={(event) => setSkills((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, value: Number(event.target.value) } : item))} className="w-full accent-indigo-400" /></div>)}</div><p className="mt-4 text-center text-[11px] text-slate-600">No answer is wrong. These inputs establish a baseline for your first score.</p></StepFrame>}
      <div className="mt-10 flex items-center justify-between"><button onClick={back} disabled={step === 1} className={`inline-flex items-center gap-2 rounded-xl px-4 py-3 text-sm font-medium transition ${step === 1 ? "invisible" : "text-slate-500 hover:text-white"}`}><ArrowLeft size={15} />Back</button>{step < 4 ? <button onClick={next} className="inline-flex items-center gap-2 rounded-xl bg-indigo-500 px-5 py-3 text-sm font-semibold text-white shadow-lg shadow-indigo-500/20 transition hover:bg-indigo-400">Continue <ArrowRight size={15} /></button> : <button onClick={finish} className="inline-flex items-center gap-2 rounded-xl bg-emerald-400 px-5 py-3 text-sm font-semibold text-slate-950 shadow-lg shadow-emerald-400/15 transition hover:bg-emerald-300">See my readiness score <Check size={15} /></button>}</div>
      <div className="mt-16 flex items-center justify-center gap-2 text-[11px] text-slate-600"><span className="grid h-5 w-5 place-items-center rounded bg-white/[0.05] text-slate-400">{step}</span> We’ll never use identity attributes to evaluate your fit.</div>
    </div></div></div>;
}
function StepFrame({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children: React.ReactNode }) { return <div className="rise"><div className="mb-8"><p className="mb-3 text-[11px] font-semibold uppercase tracking-[0.18em] text-indigo-300">{eyebrow}</p><h1 className="font-display text-4xl font-semibold tracking-[-0.05em] text-white sm:text-5xl">{title}</h1><p className="mt-3 max-w-xl text-sm leading-6 text-slate-500">{description}</p></div>{children}</div>; }
