import { ArrowRight, CheckCircle2, Info, Sparkles, TrendingUp, Zap } from "lucide-react";
import { ActionLink, Card, PageHeader, ProgressBar } from "@/components/AppShell";
import { Link } from "wouter";

const skills = [
  { name: "Python & REST APIs", current: 91, required: 78, state: "Strength", description: "Your production API work is above the role bar." },
  { name: "Testing & quality", current: 78, required: 72, state: "Strength", description: "Strong release ownership and automated testing signal." },
  { name: "System design", current: 64, required: 76, state: "Focus", description: "Deepen distributed systems trade-off reasoning." },
  { name: "Cloud architecture", current: 43, required: 70, state: "Priority", description: "The highest-leverage gap for your target role." },
  { name: "Observability", current: 39, required: 65, state: "Priority", description: "Build confidence with SLOs, tracing, and incident loops." },
  { name: "Security & IAM", current: 46, required: 61, state: "Focus", description: "Practice least-privilege patterns in deployed services." },
];

export default function CandidateGaps() { return <div className="mx-auto max-w-[1440px] px-5 py-8 lg:px-9 lg:py-10"><PageHeader eyebrow="Role fit · Software Engineer" title="Your skill gaps, made visible." description="Current signal compared with the capability bar for a Backend Engineer at your experience level." action={<Link href="/candidate/roadmap" className="inline-flex items-center gap-2 rounded-xl bg-indigo-500 px-4 py-3 text-xs font-semibold text-white shadow-lg shadow-indigo-500/20 transition hover:bg-indigo-400">Build my roadmap <ArrowRight size={14} /></Link>} />
  <div className="mb-5 grid gap-5 md:grid-cols-3"><Insight icon={TrendingUp} eyebrow="Above bar" value="2 skills" body="Your API and quality signals are already role-ready." tone="emerald" /><Insight icon={Zap} eyebrow="Highest leverage" value="Cloud architecture" body="A 4-week sprint can move the signal by 12–16 points." tone="amber" /><Insight icon={Sparkles} eyebrow="Profile confidence" value="92% clear" body="Enough evidence to make the next recommendation precise." tone="indigo" /></div>
  <Card className="overflow-hidden"><div className="flex flex-col justify-between gap-4 border-b border-white/[0.06] p-6 sm:flex-row sm:items-center sm:px-7"><div><h2 className="font-display text-xl font-semibold text-white">Capability comparison</h2><p className="mt-1 text-xs text-slate-500">The role bar is calibrated to your target role and experience level.</p></div><div className="flex items-center gap-5 text-[11px] text-slate-500"><span className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-indigo-400" />Your current</span><span className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-slate-500" />Role bar</span></div></div><div className="divide-y divide-white/[0.05]">{skills.map((skill) => <div key={skill.name} className="grid gap-5 p-6 sm:grid-cols-[1fr_1.3fr_auto] sm:items-center sm:px-7"><div><div className="flex items-center gap-2"><h3 className="text-sm font-semibold text-slate-200">{skill.name}</h3>{skill.state === "Strength" ? <CheckCircle2 size={14} className="text-emerald-300" /> : <span className={`rounded-full px-2 py-0.5 text-[9px] font-semibold uppercase tracking-wider ${skill.state === "Priority" ? "bg-amber-400/10 text-amber-300" : "bg-indigo-400/10 text-indigo-300"}`}>{skill.state}</span>}</div><p className="mt-1 text-[11px] text-slate-600">{skill.description}</p></div><div className="space-y-2"><CompareBar value={skill.current} target={skill.required} /><div className="flex justify-between font-mono text-[10px] text-slate-600"><span>Your signal <span className="text-indigo-300">{skill.current}</span></span><span>Role bar <span className="text-slate-400">{skill.required}</span></span></div></div><div className="text-right"><span className={`font-display text-xl font-semibold ${skill.current >= skill.required ? "text-emerald-300" : "text-amber-300"}`}>{skill.current >= skill.required ? "+" : "−"}{Math.abs(skill.current - skill.required)}</span><p className="mt-1 text-[10px] text-slate-600">{skill.current >= skill.required ? "above bar" : "to close"}</p></div></div>)}</div></Card>
  <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_.8fr]"><Card className="p-6 sm:p-7"><div className="mb-5 flex items-start justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-indigo-300">How to read this</p><h2 className="mt-2 font-display text-xl font-semibold text-white">A gap is a direction, not a verdict.</h2></div><Info size={17} className="text-slate-600" /></div><p className="max-w-2xl text-sm leading-6 text-slate-500">We compare role-relevant skills using a deterministic weighted model. Your identity attributes never enter the calculation. The result is designed to help you prioritize—not to make a final decision about your future.</p></Card><Card className="p-6 sm:p-7"><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-indigo-300">Ready for action?</p><h2 className="mt-2 font-display text-xl font-semibold text-white">Turn gaps into a sprint.</h2><p className="mt-2 text-sm leading-6 text-slate-500">Get a 4-week checklist with projects and proof points.</p><Link href="/candidate/roadmap" className="mt-5 inline-flex items-center gap-2 text-xs font-semibold text-indigo-300 hover:text-indigo-200">Open my roadmap <ArrowRight size={14} /></Link></Card></div>
</div>; }
function CompareBar({ value, target }: { value: number; target: number }) { return <div className="relative h-3 overflow-hidden rounded-full bg-white/[0.06]"><div className="absolute inset-y-0 left-0 rounded-full bg-slate-500/45" style={{ width: `${target}%` }} /><div className="absolute inset-y-0 left-0 rounded-full bg-indigo-400" style={{ width: `${value}%` }} /><span className="absolute inset-y-[-2px] w-px bg-white/70" style={{ left: `${target}%` }} /></div>; }
function Insight({ icon: Icon, eyebrow, value, body, tone }: { icon: React.ElementType; eyebrow: string; value: string; body: string; tone: "emerald" | "amber" | "indigo" }) { return <Card className="p-5"><div className="mb-5 flex items-center justify-between"><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-slate-500">{eyebrow}</p><span className={`grid h-8 w-8 place-items-center rounded-xl ${tone === "emerald" ? "bg-emerald-400/10 text-emerald-300" : tone === "amber" ? "bg-amber-400/10 text-amber-300" : "bg-indigo-400/10 text-indigo-300"}`}><Icon size={16} /></span></div><p className="font-display text-xl font-semibold text-white">{value}</p><p className="mt-2 text-xs leading-5 text-slate-500">{body}</p></Card>; }
