import { useState } from "react";
import { ArrowRight, BookOpen, Check, CheckCircle2, ChevronDown, Circle, ExternalLink, Flag, Lightbulb, Play, Sparkles } from "lucide-react";
import { Card, PageHeader, ProgressBar, SuccessPill } from "@/components/AppShell";
import { Link } from "wouter";

const weeks = [
  { number: "01", title: "Make systems visible", subtitle: "Architecture foundations", status: "complete", actions: ["Sketch a checkout service on a whiteboard", "Write down 3 consistency trade-offs", "Watch: Designing reliable APIs · 18 min"] },
  { number: "02", title: "Instrument the signal", subtitle: "Observability & SLOs", status: "active", actions: ["Define SLOs for your sample API", "Add structured logs and a trace ID", "Write a one-page incident review"] },
  { number: "03", title: "Secure the path", subtitle: "IAM & service boundaries", status: "upcoming", actions: ["Map least-privilege roles for your API", "Add token rotation to the sample service", "Review: threat modeling quickstart"] },
  { number: "04", title: "Ship the proof", subtitle: "Portfolio & interview story", status: "upcoming", actions: ["Package your architecture case study", "Practice a 10-minute walkthrough", "Run a targeted mock interview"] },
];

export default function CandidateRoadmap() { const [done, setDone] = useState<string[]>(["Sketch a checkout service on a whiteboard", "Write down 3 consistency trade-offs", "Watch: Designing reliable APIs · 18 min"]); const toggle = (action: string) => setDone((items) => items.includes(action) ? items.filter((item) => item !== action) : [...items, action]); const completeCount = done.length; return <div className="mx-auto max-w-[1440px] px-5 py-8 lg:px-9 lg:py-10"><PageHeader eyebrow="Your 4-week sprint" title="A roadmap you can finish." description="Focused actions to close your top gaps, with a proof point at the end of every week." action={<Link href="/candidate/interview" className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.03] px-4 py-3 text-xs font-semibold text-slate-300 hover:border-indigo-400/30 hover:text-white"><Play size={14} className="text-emerald-300" />Practice interview</Link>} />
  <div className="grid gap-5 xl:grid-cols-[1fr_330px]"><div className="space-y-4">{weeks.map((week) => <Card key={week.number} className={`overflow-hidden ${week.status === "active" ? "border-indigo-400/30" : ""}`}><div className="flex items-start gap-5 p-6 sm:p-7"><div className={`grid h-11 w-11 shrink-0 place-items-center rounded-2xl font-mono text-xs font-semibold ${week.status === "complete" ? "bg-emerald-400/10 text-emerald-300" : week.status === "active" ? "bg-indigo-400 text-white" : "bg-white/[0.05] text-slate-500"}`}>{week.status === "complete" ? <Check size={17} /> : week.number}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-display text-lg font-semibold text-white">{week.title}</h2>{week.status === "complete" && <SuccessPill>Complete</SuccessPill>}{week.status === "active" && <span className="rounded-full bg-indigo-400/10 px-2.5 py-1 text-[11px] font-semibold text-indigo-300">In progress</span>}</div><p className="mt-1 text-xs text-slate-500">{week.subtitle}</p>{week.status !== "upcoming" && <div className="mt-6 space-y-3">{week.actions.map((action) => <button key={action} onClick={() => toggle(action)} className="flex w-full items-center gap-3 text-left"><span className={`grid h-5 w-5 shrink-0 place-items-center rounded-full border ${done.includes(action) ? "border-emerald-400 bg-emerald-400 text-slate-950" : "border-white/15 text-transparent"}`}>{done.includes(action) ? <Check size={12} strokeWidth={3} /> : <Circle size={10} />}</span><span className={`text-xs transition ${done.includes(action) ? "text-slate-500 line-through" : "text-slate-300 hover:text-white"}`}>{action}</span>{action.includes("Watch") && <Play size={12} className="ml-auto text-indigo-300" />}</button>)}</div>}{week.status === "upcoming" && <div className="mt-5 flex items-center gap-2 text-xs text-slate-600"><Circle size={14} />Unlocks when Week {Number(week.number) - 1} is complete</div>}</div><ChevronDown size={17} className={`mt-1 shrink-0 ${week.status === "upcoming" ? "text-slate-700" : "text-slate-500"}`} /></div>{week.status === "active" && <div className="border-t border-indigo-400/10 bg-indigo-400/[0.04] px-6 py-3.5 sm:px-7"><div className="flex items-center justify-between text-[11px]"><span className="flex items-center gap-2 text-indigo-200/70"><Lightbulb size={13} />Proof point: an observable API with one clear SLO</span><span className="font-mono text-indigo-300">{week.actions.filter((action) => done.includes(action)).length}/{week.actions.length}</span></div></div>}</Card>)}</div>
  <div className="space-y-5"><Card className="p-6"><div className="mb-6 flex items-start justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-indigo-300">Sprint progress</p><h2 className="mt-2 font-display text-3xl font-semibold text-white">{completeCount}<span className="text-base text-slate-600"> / 12</span></h2><p className="mt-1 text-xs text-slate-500">actions completed</p></div><span className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-400/10 text-emerald-300"><Flag size={16} /></span></div><ProgressBar value={(completeCount / 12) * 100} color="emerald" /><div className="mt-4 flex justify-between text-[10px] text-slate-600"><span>Started Sep 01</span><span>Due Sep 28</span></div></Card><Card className="p-6"><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-indigo-300">The why</p><h2 className="mt-2 font-display text-xl font-semibold text-white">Small proof beats big claims.</h2><p className="mt-3 text-xs leading-5 text-slate-500">Each action is selected to create something you can explain, show, or apply—not just consume.</p><div className="mt-5 space-y-3"><RoadmapMeta icon={Sparkles} label="Expected readiness lift" value="+12–16 pts" /><RoadmapMeta icon={BookOpen} label="Target gap" value="Cloud architecture" /><RoadmapMeta icon={ExternalLink} label="Evidence to create" value="1 case study" /></div></Card><Card className="border-indigo-400/20 bg-indigo-400/[0.06] p-6"><p className="text-xs font-semibold text-indigo-200">Need a nudge?</p><p className="mt-2 text-xs leading-5 text-indigo-100/60">Run a mock interview after Week 2 to see if your explanation depth is catching up.</p><Link href="/candidate/interview" className="mt-4 inline-flex items-center gap-2 text-xs font-semibold text-indigo-300">Start practice <ArrowRight size={13} /></Link></Card></div></div></div>; }
function RoadmapMeta({ icon: Icon, label, value }: { icon: React.ElementType; label: string; value: string }) { return <div className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-white/[0.05] text-slate-400"><Icon size={14} /></span><span className="min-w-0 flex-1"><span className="block text-[10px] text-slate-600">{label}</span><span className="mt-0.5 block text-xs font-medium text-slate-300">{value}</span></span></div>; }
