import { useState } from "react";
import { Activity, ArrowUpRight, BarChart3, BookOpen, BrainCircuit, ChevronRight, Cloud, Code2, Info, Layers3, LockKeyhole, Sparkles, Target, X } from "lucide-react";
import { ActionLink, Card, PageHeader, ProgressBar, StatCard, SuccessPill } from "@/components/AppShell";
import { Link } from "wouter";

const evidence = [
  { label: "Python & REST APIs", value: 91, delta: "+13", tone: "emerald" as const, note: "Strong evidence across 4 projects and 2 production deployments." },
  { label: "Testing & quality", value: 78, delta: "+8", tone: "emerald" as const, note: "Consistent ownership of CI checks, unit tests, and release quality." },
  { label: "System design", value: 64, delta: "−4", tone: "indigo" as const, note: "Good service decomposition signal; distributed trade-offs need more depth." },
  { label: "Cloud architecture", value: 43, delta: "−15", tone: "amber" as const, note: "The clearest opportunity: IAM, observability, and cost-aware design." },
];

export default function CandidateDashboard() {
  const [drawerOpen, setDrawerOpen] = useState(false);
  return <div className="mx-auto max-w-[1440px] px-5 py-8 lg:px-9 lg:py-10"><PageHeader eyebrow="Monday, 03 September 2026" title="Good morning, Alex." description="Here’s the clearest view of your path to Backend Engineer." action={<Link href="/candidate/gaps" className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.03] px-4 py-3 text-xs font-semibold text-slate-300 transition hover:border-indigo-400/30 hover:text-white"><Target size={15} className="text-indigo-300" />View role fit</Link>} />
    <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Card className="overflow-hidden"><div className="grid items-center gap-8 p-6 sm:p-8 md:grid-cols-[auto_1fr] md:p-9"><div className="relative grid h-44 w-44 place-items-center rounded-full" style={{background: 'conic-gradient(#10B981 0 78%, rgba(255,255,255,.07) 78% 100%)'}}><div className="grid h-[148px] w-[148px] place-items-center rounded-full bg-[#111725]"><div className="text-center"><div className="font-display text-5xl font-semibold tracking-[-0.06em] text-white">78</div><div className="mt-1 text-xs text-slate-500">out of 100</div></div></div><span className="absolute -right-1 top-5 rounded-full border border-emerald-400/20 bg-emerald-400/10 px-2 py-1 text-[10px] font-semibold text-emerald-300">+8 this month</span></div><div><div className="mb-4 flex items-center gap-2"><SuccessPill>Strong trajectory</SuccessPill><span className="text-[11px] text-slate-600">Updated 2h ago</span></div><h2 className="font-display text-2xl font-semibold tracking-[-0.04em] text-white">Your readiness signal is building.</h2><p className="mt-2 max-w-lg text-sm leading-6 text-slate-500">You’re showing a strong backend foundation. Strengthen cloud architecture and you’ll move closer to the role bar.</p><button onClick={() => setDrawerOpen(true)} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-indigo-500 px-4 py-3 text-xs font-semibold text-white shadow-lg shadow-indigo-500/20 transition hover:bg-indigo-400"><Sparkles size={15} />Why this score? <ChevronRight size={14} /></button></div></div><div className="grid grid-cols-3 border-t border-white/[0.06] bg-white/[0.015]"><div className="p-4 text-center sm:p-5"><p className="font-display text-lg font-semibold text-white">14</p><p className="mt-1 text-[10px] uppercase tracking-[0.12em] text-slate-600">skills mapped</p></div><div className="border-x border-white/[0.06] p-4 text-center sm:p-5"><p className="font-display text-lg font-semibold text-white">4<span className="text-sm text-slate-500"> wk</span></p><p className="mt-1 text-[10px] uppercase tracking-[0.12em] text-slate-600">next sprint</p></div><div className="p-4 text-center sm:p-5"><p className="font-display text-lg font-semibold text-emerald-300">92%</p><p className="mt-1 text-[10px] uppercase tracking-[0.12em] text-slate-600">profile clarity</p></div></div></Card>
      <Card className="p-6 sm:p-7"><div className="mb-6 flex items-start justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-indigo-300">Next best action</p><h2 className="mt-2 font-display text-xl font-semibold text-white">Close your cloud gap.</h2></div><span className="grid h-9 w-9 place-items-center rounded-xl bg-amber-400/10 text-amber-300"><Cloud size={17} /></span></div><p className="text-sm leading-6 text-slate-500">A focused 4-week sprint on IAM, observability, and architecture trade-offs could add <span className="font-semibold text-amber-300">12–16 points</span> to your role readiness.</p><div className="mt-7"><div className="mb-2 flex justify-between text-[11px]"><span className="text-slate-400">Cloud architecture</span><span className="text-amber-300">43 / 70 target</span></div><ProgressBar value={61} color="amber" /></div><Link href="/candidate/roadmap" className="mt-7 inline-flex w-full items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/[0.02] py-3 text-xs font-semibold text-slate-300 transition hover:border-indigo-400/30 hover:text-white">Open your roadmap <ArrowUpRight size={14} /></Link><p className="mt-5 flex items-center gap-2 text-[11px] text-slate-600"><LockKeyhole size={12} />Recommendations use skills only, never identity signals.</p></Card></div>
    <div className="mt-5 grid gap-5 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Role fit" value="78%" change="+8 pts" icon={Target} tone="indigo" /><StatCard label="Skills above bar" value="8 / 14" change="+2 this month" icon={Code2} tone="emerald" /><StatCard label="Learning momentum" value="82%" change="On track" icon={Activity} tone="emerald" /><StatCard label="Interview confidence" value="68%" change="Practice next" icon={BrainCircuit} tone="amber" /></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Card className="p-6 sm:p-7"><div className="mb-7 flex items-end justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-indigo-300">Evidence map</p><h2 className="mt-2 font-display text-xl font-semibold text-white">The signal behind your score</h2></div><Link href="/candidate/gaps" className="hidden sm:block"><ActionLink href="/candidate/gaps">See all skills</ActionLink></Link></div><div className="space-y-6">{evidence.map((item) => <div key={item.label}><div className="mb-2.5 flex items-center justify-between"><div><span className="text-sm font-medium text-slate-200">{item.label}</span><span className={`ml-2 text-[10px] font-semibold ${item.tone === "amber" ? "text-amber-300" : item.tone === "emerald" ? "text-emerald-300" : "text-indigo-300"}`}>{item.delta}</span></div><span className="font-mono text-xs text-slate-400">{item.value}</span></div><ProgressBar value={item.value} color={item.tone} /><p className="mt-2 text-[11px] text-slate-600">{item.note}</p></div>)}</div></Card><Card className="p-6 sm:p-7"><div className="mb-7 flex items-start justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-indigo-300">Keep moving</p><h2 className="mt-2 font-display text-xl font-semibold text-white">Your workspace</h2></div><Layers3 size={18} className="text-slate-600" /></div><div className="space-y-3"><WorkspaceItem href="/candidate/roadmap" icon={BookOpen} title="Continue your roadmap" detail="Week 2 · observability patterns" tone="indigo" /><WorkspaceItem href="/candidate/interview" icon={BrainCircuit} title="Run a mock interview" detail="Backend fundamentals · 12 min" tone="emerald" /><WorkspaceItem href="/candidate/gaps" icon={BarChart3Icon} title="Review skill gaps" detail="6 opportunities to explore" tone="amber" /></div></Card></div>
    {drawerOpen && <div className="fixed inset-0 z-50 flex justify-end"><button className="absolute inset-0 bg-black/60 backdrop-blur-sm" aria-label="Close explanation" onClick={() => setDrawerOpen(false)} /><aside className="relative h-full w-full max-w-xl overflow-y-auto border-l border-white/10 bg-[#101624] p-6 shadow-2xl sm:p-9"><div className="mb-10 flex items-start justify-between"><div><div className="mb-3 flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.16em] text-indigo-300"><Sparkles size={13} />Explainability</div><h2 className="font-display text-3xl font-semibold tracking-[-0.04em] text-white">Why this score?</h2><p className="mt-2 text-sm text-slate-500">Every signal is inspectable. No hidden features, no pedigree shortcuts.</p></div><button className="rounded-xl border border-white/10 p-2 text-slate-400 hover:text-white" onClick={() => setDrawerOpen(false)} aria-label="Close"><X size={18} /></button></div><div className="mb-8 rounded-2xl border border-emerald-400/20 bg-emerald-400/[0.06] p-5"><div className="flex items-end justify-between"><div><p className="text-[11px] uppercase tracking-[0.16em] text-emerald-200/70">Overall readiness</p><p className="mt-1 font-display text-4xl font-semibold text-white">78<span className="text-lg text-slate-500"> / 100</span></p></div><span className="text-xs font-semibold text-emerald-300">Strong trajectory</span></div><div className="mt-4"><ProgressBar value={78} color="emerald" /></div></div><EvidenceSection title="Positive skill evidence" tone="emerald" items={evidence.filter((item) => item.tone === "emerald")} /><EvidenceSection title="Limitations to work on" tone="amber" items={evidence.filter((item) => item.tone !== "emerald")} /><div className="mt-8 border-t border-white/[0.07] pt-6"><p className="flex gap-2 text-xs leading-5 text-slate-500"><Info size={15} className="mt-0.5 shrink-0 text-indigo-300" />The score is a deterministic weighted comparison of your skills to the selected role bar. It does not use your name, gender, college, email, or location.</p></div><Link href="/candidate/gaps" onClick={() => setDrawerOpen(false)} className="mt-7 inline-flex w-full items-center justify-center rounded-xl bg-indigo-500 py-3 text-xs font-semibold text-white">See the full skill gap analysis <ArrowUpRight size={14} className="ml-2" /></Link></aside></div>}
  </div>;
}
function EvidenceSection({ title, tone, items }: { title: string; tone: "emerald" | "amber"; items: typeof evidence }) { return <section className="mb-8"><div className="mb-4 flex items-center gap-2"><span className={`h-1.5 w-1.5 rounded-full ${tone === "emerald" ? "bg-emerald-400" : "bg-amber-400"}`} /><h3 className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-400">{title}</h3></div><div className="space-y-3">{items.map((item) => <div key={item.label} className="rounded-2xl border border-white/[0.07] bg-white/[0.025] p-4"><div className="flex items-center justify-between"><p className="text-sm font-medium text-slate-200">{item.label}</p><span className={`font-mono text-xs ${tone === "emerald" ? "text-emerald-300" : "text-amber-300"}`}>{item.value}</span></div><p className="mt-2 text-[11px] leading-5 text-slate-500">{item.note}</p></div>)}</div></section>; }
function WorkspaceItem({ href, icon: Icon, title, detail, tone }: { href: string; icon: React.ElementType; title: string; detail: string; tone: "indigo" | "emerald" | "amber" }) { return <Link href={href} className="flex items-center gap-3 rounded-2xl border border-white/[0.07] bg-white/[0.02] p-3 transition hover:border-white/15"><span className={`grid h-9 w-9 place-items-center rounded-xl ${tone === "indigo" ? "bg-indigo-400/10 text-indigo-300" : tone === "emerald" ? "bg-emerald-400/10 text-emerald-300" : "bg-amber-400/10 text-amber-300"}`}><Icon size={16} /></span><span className="min-w-0 flex-1"><span className="block text-xs font-semibold text-slate-200">{title}</span><span className="mt-1 block truncate text-[11px] text-slate-600">{detail}</span></span><ChevronRight size={15} className="text-slate-600" /></Link>; }
function BarChart3Icon(props: React.ComponentProps<typeof BarChart3>) { return <BarChart3 {...props} />; }
