import { Link } from "wouter";
import { ArrowRight, BarChart3, Check, ChevronRight, CirclePlay, Eye, GitBranch, Menu, ShieldCheck, Sparkles, Target, UserRound, UsersRound, X } from "lucide-react";
import { useState } from "react";

const steps = [
  { n: "01", title: "Build your signal", body: "Turn experience into a structured, identity-blind skills profile.", icon: UserRound },
  { n: "02", title: "See the why", body: "Get a readiness score with evidence you can inspect and act on.", icon: Eye },
  { n: "03", title: "Close the gaps", body: "Follow a focused roadmap tailored to the role you want next.", icon: GitBranch },
  { n: "04", title: "Hire with context", body: "Give teams a fairer signal and a human decision trail.", icon: ShieldCheck },
];

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  return <div className="min-h-screen overflow-hidden bg-[#0B0F19] text-slate-100">
    <div className="pointer-events-none fixed left-1/2 top-[-240px] h-[600px] w-[900px] -translate-x-1/2 rounded-full bg-indigo-600/10 blur-[120px]" />
    <nav className="relative z-10 mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-10"><Link href="/" className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-indigo-500 text-white shadow-lg shadow-indigo-500/25"><CompassMark /></span><span><span className="block font-display text-[15px] font-semibold tracking-tight">CareerCompass</span><span className="block text-[10px] font-semibold uppercase tracking-[0.2em] text-indigo-300">AI / Intelligence</span></span></Link><div className="hidden items-center gap-8 text-xs text-slate-400 md:flex"><a href="#product" className="transition hover:text-white">Product</a><a href="#how-it-works" className="transition hover:text-white">How it works</a><a href="#principles" className="transition hover:text-white">Our principles</a></div><div className="hidden items-center gap-3 md:flex"><Link href="/candidate/dashboard" className="rounded-xl px-3 py-2 text-xs font-medium text-slate-400 transition hover:text-white">Sign in</Link><Link href="/candidate/onboarding" className="rounded-xl bg-indigo-500 px-4 py-2.5 text-xs font-semibold text-white shadow-lg shadow-indigo-500/20 transition hover:bg-indigo-400">Start exploring <ArrowRight size={14} className="ml-1 inline" /></Link></div><button className="rounded-xl border border-white/10 p-2 text-slate-300 md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label="Open menu">{menuOpen ? <X size={18} /> : <Menu size={18} />}</button></nav>
    {menuOpen && <div className="relative z-20 mx-6 rounded-2xl border border-white/10 bg-[#111725] p-4 md:hidden"><div className="grid gap-3 text-sm text-slate-300"><a href="#product" onClick={() => setMenuOpen(false)}>Product</a><a href="#how-it-works" onClick={() => setMenuOpen(false)}>How it works</a><Link href="/candidate/onboarding">Start exploring <ArrowRight size={14} className="ml-1 inline" /></Link></div></div>}
    <main>
      <section className="relative mx-auto grid max-w-7xl items-center gap-16 px-6 pb-24 pt-14 lg:grid-cols-[1.02fr_.98fr] lg:px-10 lg:pb-32 lg:pt-24"><div className="relative z-10 rise"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-indigo-400/20 bg-indigo-400/[0.08] px-3 py-1.5 text-[11px] font-semibold tracking-wide text-indigo-200"><span className="h-1.5 w-1.5 rounded-full bg-emerald-400 pulse-dot" />A clearer signal for what comes next</div><h1 className="max-w-3xl font-display text-5xl font-semibold leading-[1.05] tracking-[-0.06em] text-white sm:text-6xl lg:text-[76px]">Careers should be <span className="bg-gradient-to-r from-indigo-300 via-violet-300 to-indigo-500 bg-clip-text text-transparent">explainable.</span></h1><p className="mt-7 max-w-xl text-base leading-7 text-slate-400 sm:text-lg">CareerCompass AI turns potential into a plan—and hiring signals into decisions people can trust.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/candidate/onboarding" className="inline-flex items-center justify-center rounded-xl bg-indigo-500 px-5 py-3.5 text-sm font-semibold text-white shadow-xl shadow-indigo-500/20 transition hover:-translate-y-0.5 hover:bg-indigo-400">Find your next move <ArrowRight size={16} className="ml-2" /></Link><a href="#how-it-works" className="inline-flex items-center justify-center rounded-xl border border-white/[0.1] bg-white/[0.02] px-5 py-3.5 text-sm font-medium text-slate-300 transition hover:border-white/20 hover:text-white"><CirclePlay size={16} className="mr-2 text-indigo-300" /> See how it works</a></div><div className="mt-10 flex flex-wrap items-center gap-x-6 gap-y-3 text-xs text-slate-500"><span className="flex items-center gap-2"><Check size={14} className="text-emerald-400" />Identity-blind by design</span><span className="flex items-center gap-2"><Check size={14} className="text-emerald-400" />Human review, always</span></div></div>
        <div className="relative rise [animation-delay:120ms]"><div className="absolute -right-10 top-0 h-64 w-64 rounded-full bg-indigo-500/15 blur-[80px]" /><div className="relative overflow-hidden rounded-[26px] border border-white/[0.1] bg-[#111725] p-3 shadow-2xl shadow-black/40 glow-indigo"><div className="rounded-[19px] border border-white/[0.07] bg-[#0D121F] p-5 sm:p-6"><div className="mb-6 flex items-center justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-600">Alex's career signal</p><p className="mt-1 text-sm font-medium text-slate-300">Software Engineer · 3–5 years</p></div><span className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-400/10 text-emerald-300"><BarChart3 size={17} /></span></div><div className="flex items-end gap-4"><div className="relative grid h-32 w-32 place-items-center rounded-full" style={{background: 'conic-gradient(#10B981 0 78%, rgba(255,255,255,.07) 78% 100%)'}}><div className="grid h-[105px] w-[105px] place-items-center rounded-full bg-[#0D121F]"><div className="text-center"><p className="font-display text-3xl font-semibold text-white">78%</p><p className="text-[10px] text-slate-500">readiness</p></div></div></div><div className="pb-1"><p className="text-xs text-slate-500">You’re building a strong</p><p className="mt-1 text-lg font-semibold text-white">backend foundation</p><p className="mt-2 text-xs text-emerald-300"><span className="mr-1">↑</span>+8 pts this month</p></div></div><div className="mt-8 space-y-4"><SignalBar label="Python & APIs" value={91} color="emerald" /><SignalBar label="System design" value={64} color="indigo" /><SignalBar label="Cloud architecture" value={43} color="amber" /></div><div className="mt-6 rounded-xl border border-indigo-400/15 bg-indigo-400/[0.06] p-3"><div className="flex gap-2.5"><Sparkles size={15} className="mt-0.5 shrink-0 text-indigo-300" /><p className="text-[11px] leading-5 text-indigo-100/80"><span className="font-semibold text-indigo-200">Why this score?</span> Your API depth and production ownership are carrying the signal. A focused cloud sprint can close the biggest gap.</p></div></div></div></div><div className="absolute -bottom-5 -left-6 hidden rounded-2xl border border-white/10 bg-[#151B2A] px-4 py-3 shadow-xl sm:block"><div className="flex items-center gap-3"><div className="grid h-8 w-8 place-items-center rounded-lg bg-emerald-400/10 text-emerald-300"><ShieldCheck size={16} /></div><div><p className="text-[10px] uppercase tracking-wider text-slate-600">Fairness check</p><p className="text-xs font-medium text-slate-200">Passed · no proxy signals</p></div></div></div></div>
      </section>
      <section id="product" className="border-y border-white/[0.06] bg-[#0D121F]/60"><div className="mx-auto grid max-w-7xl gap-10 px-6 py-14 lg:grid-cols-[.8fr_1.2fr] lg:px-10"><div><p className="mb-3 text-[11px] font-semibold uppercase tracking-[0.2em] text-indigo-300">The problem with black boxes</p><h2 className="max-w-md font-display text-3xl font-semibold leading-tight tracking-[-0.04em] text-white">A score without a why is just a guess.</h2></div><div className="grid gap-8 sm:grid-cols-3"><MiniPrinciple icon={Target} title="Know your signal" body="See the evidence behind every recommendation, not just an output." /><MiniPrinciple icon={GitBranch} title="Make progress visible" body="Translate gaps into an actionable sequence you can actually follow." /><MiniPrinciple icon={ShieldCheck} title="Keep humans in" body="Fairness audits and review overrides make accountability explicit." /></div></div></section>
      <section id="how-it-works" className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><div className="mb-12 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-3 text-[11px] font-semibold uppercase tracking-[0.2em] text-indigo-300">How it works</p><h2 className="font-display text-3xl font-semibold tracking-[-0.04em] text-white sm:text-4xl">From uncertainty to next step.</h2></div><p className="max-w-sm text-sm leading-6 text-slate-500">One calm workspace for candidates finding their edge and teams building fairer pipelines.</p></div><div className="grid gap-4 md:grid-cols-4">{steps.map((step) => { const Icon = step.icon; return <div key={step.n} className="group rounded-2xl border border-white/[0.07] bg-[#111725] p-5 transition hover:-translate-y-1 hover:border-indigo-400/30"><div className="mb-12 flex items-start justify-between"><span className="font-mono text-[11px] text-indigo-300">{step.n}</span><Icon size={18} className="text-slate-600 transition group-hover:text-indigo-300" /></div><h3 className="font-display text-lg font-semibold text-white">{step.title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{step.body}</p></div>})}</div></section>
      <section id="principles" className="mx-6 mb-12 overflow-hidden rounded-[28px] border border-indigo-400/20 bg-gradient-to-br from-indigo-500/[0.15] via-[#111725] to-[#111725] lg:mx-auto lg:max-w-7xl"><div className="grid items-center gap-8 px-7 py-10 sm:px-12 lg:grid-cols-[1fr_auto] lg:py-14"><div><p className="mb-3 text-[11px] font-semibold uppercase tracking-[0.2em] text-indigo-200">Start with clarity</p><h2 className="max-w-2xl font-display text-3xl font-semibold tracking-[-0.04em] text-white sm:text-4xl">Your next move is closer than you think.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-indigo-100/60">Explore a demo workspace to see how a transparent readiness signal can change the way you plan—or hire.</p></div><Link href="/candidate/onboarding" className="inline-flex items-center justify-center rounded-xl bg-white px-5 py-3.5 text-sm font-semibold text-slate-950 transition hover:bg-indigo-50">Explore the demo <ChevronRight size={16} className="ml-1" /></Link></div></section>
    </main><footer className="mx-auto flex max-w-7xl flex-col gap-3 border-t border-white/[0.06] px-6 py-8 text-xs text-slate-600 sm:flex-row sm:items-center sm:justify-between lg:px-10"><span>© 2026 CareerCompass AI</span><span>Built for better decisions, not louder predictions.</span></footer>
  </div>;
}
function CompassMark() { return <svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.4"><circle cx="12" cy="12" r="8.5"/><path d="m15.5 8.5-2.2 4.8-4.8 2.2 2.2-4.8 4.8-2.2Z" /></svg>; }
function SignalBar({ label, value, color }: { label: string; value: number; color: "emerald" | "indigo" | "amber" }) { return <div><div className="mb-2 flex justify-between text-[11px]"><span className="text-slate-400">{label}</span><span className={color === "emerald" ? "text-emerald-300" : color === "amber" ? "text-amber-300" : "text-indigo-300"}>{value}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/[0.07]"><div className={`h-full rounded-full ${color === "emerald" ? "bg-emerald-400" : color === "amber" ? "bg-amber-400" : "bg-indigo-400"}`} style={{ width: `${value}%` }} /></div></div>; }
function MiniPrinciple({ icon: Icon, title, body }: { icon: React.ElementType; title: string; body: string }) { return <div><Icon size={18} className="mb-4 text-indigo-300" /><h3 className="text-sm font-semibold text-slate-200">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{body}</p></div>; }
